### ISSUE TITLE
Underflow Problem with lots of loci

### ISSUE THREAD

**Issue by kwojtusik** [eriqande/rubias#29] opened 2020-09-16 18:12 UTC
Hi Eric,

I am trying to use self_assign and I keep getting an error when I try to run it where it doesn't seem to like something in the locus names, but the names are similar to what is presented on your github page so I'm not really sure what is the matter. I used the function write_rubias in the Radiator to create the Rubias file. 

This is the code I'm using:
`Allrivs_rubias_assign <- self_assign(reference = All_Rivers_Rubias, gen_start_col = 7)`

And this the error that I keep getting:
`Error in check_refmix(reference, gen_start_col, "reference") : 
  All locus columns must be of characters or integers.  These in reference are not: SSXF01000001_1__100__3957868.A2, SSXF01000001_1__101__3963326.A1, SSXF01000001_1__101__3963326.A2, SSXF01000001_1__102__3963733.A1, SSXF01000001_1__102__3963733.A2, SSXF01000001_1__103__3976661.A1, SSXF01000001_1__103__3976661.A2, SSXF01000001_1__104__3983670.A1, SSXF01000001_1__104__3983670.A2, SSXF01000001_1__105__3983736.A1, SSXF01000001_1__105__3983736.A2, SSXF01000001_1__106__3983747.A1, SSXF01000001_1__106__3983747.A2, SSXF01000001_1__107__3983751.A1, SSXF01000001_1__107__3983751.A2, SSXF01000001_1__108__4039958.A1, SSXF01000001_1__108__4039958.A2, SSXF01000001_1__109__4043463.A1, SSXF01000001_1__109__4043463.A2, SSXF01000001_1__10__428613.A1, SSXF01000001_1__10__428613.A2, SSXF01000001_1__110__4046443.A1, SSXF01000001_1__110__4046443.A2, SSXF01000001_1__111__4058814.A1, SSXF01000001_1__111__4058814.A2, SSXF01000001_1__112__4163260.A1, SSXF01000001_1__112__4163260.A2, SSXF01000001_1__113__`

Thank you for any help you can provide.

-Kris

**Comment by eriqande** [comment] 2020-09-16 18:36
Hi Kris,

I suspect that the vectors that are the columns in that tibble are of type
numeric rather than being of type integer or character.  Some new idioms in
the tidyverse make it pretty easy to correct that.  By way of example, here
I change all the locus columns in the `chinook` data set in rubias from
type "integer" to "numeric".

```r
library(tidyverse)
library(rubias)

chinook_bad <- chinook %>%
    mutate_at(vars(-(sample_type:indiv)), as.numeric)

# then if I try to use that I get a similar error
this_will_fail <- self_assign(chinook_bad, 5)

# so, we need to make all the locus columns of type integer of character
chinook_fix_int <- chinook_bad %>% mutate_at(vars(-(sample_type:indiv)),
as.integer)
chinook_fix_char <- chinook_bad %>% mutate_at(vars(-(sample_type:indiv)),
as.character)

# both of those fixed data sets work.

```
You might have a few extra non-genetic-locus columns in your data so you
might have to use something different than `vars(-(sample_type:indiv))` to
be left with nothing but genetic data columns that are being modified.

Please let me know if that fixes things for you.

eric

**Comment by eriqande** [comment] 2020-09-16 18:37
Hi Kris,

I suspect that the vectors that are the columns in that tibble are of type
numeric rather than being of type integer or character. Some new idioms in
the tidyverse make it pretty easy to correct that. By way of example, here
I change all the locus columns in the `chinook` data set in rubias from
type "integer" to "numeric".

```r
library(tidyverse)
library(rubias)

chinook_bad <- chinook %>%
mutate_at(vars(-(sample_type:indiv)), as.numeric)

# then if I try to use that I get a similar error
this_will_fail <- self_assign(chinook_bad, 5)

# so, we need to make all the locus columns of type integer of character
chinook_fix_int <- chinook_bad %>% mutate_at(vars(-(sample_type:indiv)),
as.integer)
chinook_fix_char <- chinook_bad %>% mutate_at(vars(-(sample_type:indiv)),
as.character)

# both of those fixed data sets work.

```
You might have a few extra non-genetic-locus columns in your data so you
might have to use something different than `vars(-(sample_type:indiv))` to
be left with nothing but genetic data columns that are being modified.

Please let me know if that fixes things for you.

eric

**Comment by kwojtusik** [comment] 2020-09-16 18:47
Hi Eric,

Yes, when I checked the type using "type.of", the columns were coming back as "double", which i am not familiar with, but that seemed to be the issue.

I used 
`All_Rivers_Rubias[] <- lapply(All_Rivers_Rubias, as.character)`

To convert them to characters. This is a bit less elegant than the solution you gave me, but it seemed to work as rubias ran with no errors popping up. 

I will keep your example in my files for the future. Thank you for answering so promptly. 

-Kris

**Comment by eriqande** [comment] 2020-09-16 19:22
Great.  Glad to hear that the problem is solved.

Best regards,

eric

**Comment by kwojtusik** [comment] 2020-09-16 20:22
Apologies for the additional question, but when I run it everything appears to work (i.e. no errors) but when i look at the results, this is what I get:

` A tibble: 100 x 11
   indiv collection repunit inferred_collec… inferred_repunit  scaled_likeliho…  log_likelihood  z_score
   <chr> <chr>      <chr>   <chr>            <chr>                             <dbl>                <dbl>           <dbl>
 1 R-1   Roanoke    Roanoke Roanoke          Roanoke                     NaN               -6038.            -2.87
 2 R-1   Roanoke    Roanoke Delaware         Delaware                    NaN               -6300.           -20.3 
 3 R-1   Roanoke    Roanoke Upper_Bay        Upper_Bay               NaN                -6627.           -39.3 
 4 R-1   Roanoke    Roanoke Potomac          Potomac                    NaN               -6838.           -49.0 
 5 R-1   Roanoke    Roanoke Choptank         Choptank                  NaN                -6901.            -47.2 
 6 R-1   Roanoke    Roanoke Hudson           Hudson                        NaN                -7847.            -121.  
 7 R-1   Roanoke    Roanoke Shubenacadie     Shubenacadie        NaN                 -8605.           -97.1 
 8 R-1   Roanoke    Roanoke Miramichi        Miramichi                     NaN                -8860.           -179.  
 9 R-1   Roanoke    Roanoke Kennebec         Kennebec                   NaN                 -11319.           -491.  
10 R-10  Roanoke    Roanoke Roanoke          Roanoke                    NaN                 -6083.             -2.93'

Do you have any thoughts as to the reason the results look like this?  Thank you.

-Kris

**Comment by eriqande** [comment] 2020-09-16 20:41
Hi Kris,

That looks like an underflow problem.  How many markers are you using?  I suspect quite a few.  That's all good.  I think it can be fixed by just tweaking one line of code.  Could you provide me your data set to make sure that I have fixed the problem?

**Comment by kwojtusik** [comment] 2020-09-17 14:13
Hi Eric,

Yes i am using quite a few markers, ~13,000 SNPs. I wasn't sure what type of file would be best so I created a .csv file of the rubias input. Please let me know if there is a better/easier file type you would like. Thank you!

-Kris

[All_Rivers_Rubias.csv.zip](https://github.com/eriqande/rubias/files/5239672/All_Rivers_Rubias.csv.zip)

**Closed** 2020-09-17 21:03 UTC

**Comment by eriqande** [comment] 2020-09-17 21:07
Hey Kris,

Thanks for sending me some test data.  

I fixed this in the last commit.  You can get that with:
```r
 remotes::install_github("eriqande/rubias")
```

Here were some notes when I was testing it.  With a little info about reading and writing R objects:
```r


library(tidyverse)
library(rubias)

dat <- read_csv("data/All_Rivers_Rubias.csv.gz")

# note that Kris' base R solution is way faster than
# mutate_at().  Mutate_at must carry around a bunch of other
# junk that is slowing it down.  Nice Kris!  Let's hear it
# for base R.
dat2 <- dat
dat2[] <- lapply(dat, as.character)

# Hey Kris!  If you want to save an R object that someone can be sure is
# just like the one you had.  you can use saveRDS (or the tidyverse version
# which is write_rds().  The "xz" compression is quite efficient...)

# save this as a compressed rds
dir.create("outputs/001/", showWarnings = FALSE, recursive = TRUE)
write_rds(dat2, path = "outputs/001/kris_data.rds", compress = "xz")

# that is smaller than a zipped csv and also retains all the characteristics
# of the object.

# With the standard version of rubias, this hits an underflow
# issue when computing the scaled likelihood.
SA <- self_assign(dat2, 7)

# I fixed this with a simple change on the master branch in
# commit 23cf4e34.

```

Have a great day!

**Comment by kwojtusik** [comment] 2020-09-18 14:24
That worked! Thanks Eric!

**Comment by eriqande** [comment] 2020-09-18 15:18
Excellent!  Glad to hear it.  Good luck with your project.

eric
